"""Added discogs_id unique property on artist and release tables

Revision ID: d9571082aae7
Revises: ed4bbf36b3ab
Create Date: 2023-01-16 14:23:58.918108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9571082aae7'
down_revision = 'ed4bbf36b3ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artist_discogs_id', table_name='artist')
    op.create_index(op.f('ix_artist_discogs_id'), 'artist', ['discogs_id'], unique=True)
    op.drop_index('ix_release_discogs_id', table_name='release')
    op.create_index(op.f('ix_release_discogs_id'), 'release', ['discogs_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_discogs_id'), table_name='release')
    op.create_index('ix_release_discogs_id', 'release', ['discogs_id'], unique=False)
    op.drop_index(op.f('ix_artist_discogs_id'), table_name='artist')
    op.create_index('ix_artist_discogs_id', 'artist', ['discogs_id'], unique=False)
    # ### end Alembic commands ###
