"""Added image_url column to release table

Revision ID: dfb219e40d0f
Revises: d9571082aae7
Create Date: 2023-01-16 20:17:18.614715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb219e40d0f'
down_revision = 'd9571082aae7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('image_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'image_url')
    # ### end Alembic commands ###
