"""Rename name col to title in release table

Revision ID: ec7b37286da0
Revises: dfb219e40d0f
Create Date: 2023-01-17 17:42:40.697960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7b37286da0'
down_revision = 'dfb219e40d0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('title', sa.String(length=256), nullable=False))
    op.drop_column('release', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('release', 'title')
    # ### end Alembic commands ###
